export const products = [
  {
    id: 1,
    name: "Perfect Bright Cooling Bright Jelly Facial Foam",
    category: "Face Wash",
    price: 30,
    image: "/images/products/fw1.png",
    isCart: false,
    description: "Facial foam with Berry Extract.",
  },
  {
    id: 2,
    name: "The Originote Hyalucera Moisturizer",
    category: "Moisturizer",
    price: 20,
    image: "/images/products/moist2.png",
    isCart: false,
    description: "Maintain and repair skin barrier.",
  },
  {
    id: 3,
    name: "Perfect Bright Cooling Bright Jelly Facial Foam",
    category: "Face Wash",
    price: 17,
    image: "/images/products/fw2.png",
    isCart: false,
    description: "Deeply cleanses the face and reduces dullness while boosting the radiance of your skin.",
  },
  {
    id: 4,
    name: "The Originote BHA Charcoal Clay Mask",
    category: "Face Mask",
    price: 16,
    image: "/images/products/mask.png",
    isCart: false,
    description: "A mask with a clay texture that functions to absorb oil while cleaning pores.",
  },
  {
    id: 5,
    name: "Implora Perfect Shield Sunscreen SPF 40 PA++++",
    category: "Sunscreen",
    price: 10,
    image: "/images/products/ss2.png",
    isCart: false,
    description: "To protect the skin from the dangers caused by sun exposure with a formula that helps protect the skin from UVA and UVB rays.",
  },
  {
    id: 6,
    name: "Glad2Glow 5% Blueberry Moisturizer Cream",
    category: "Moisturizer",
    price: 10,
    image: "/images/products/moist1.png",
    isCart: false,
    description: "Moisturizer with blueberry and ceramide extracts which functions to treat inflamed, reddish or sensitive skin, has a light gel texture that is easily absorbed, moisturizes the skin well and gives a cooling sensation with a refreshing blueberry scent, suitable for dry, oily or oily skin sensitive",
  },
  {
    id: 7,
    name: "Azarine Hydramax-c Sunscreen Serum SPF50 Pa++++",
    category: "Sunscreen",
    price: 10,
    image: "/images/products/ss1.png",
    isCart: false,
    description: "Sunscreen in the form of cream-gel to moisturize and protect the skin from the harmful effects of sunlight, blue light and pollution. It is formulated with 11 types of hyaluronic acid to create supple skin. Contains vitamins c & e as antioxidants.",
  },
  {
    id: 8,
    name: "Nivea Extra White Body Serum Care & Protect Deep White Essence",
    category: "Body Serum",
    price: 10,
    image: "/images/products/bserum.png",
    isCart: false,
    description: "Body Serum with SPF",
  }
];